# Generated by Django 5.0.6 on 2024-06-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_charge_expend_side_alter_charge_income_side"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="created_at",
            field=models.DateField(auto_now=True, verbose_name="创建时间"),
        ),
    ]
