# Generated by Django 5.0.6 on 2024-06-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_charge_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="created_at",
            field=models.DateField(auto_created=True, verbose_name="发生时间"),
        ),
    ]
