# Generated by Django 5.0.6 on 2024-06-15 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_alter_charge_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="charge",
            old_name="comments",
            new_name="charge_comments",
        ),
    ]
