# Generated by Django 5.0.6 on 2024-06-15 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_business_business_comments"),
        ("finance", "0007_rename_comments_charge_charge_comments"),
        ("tag", "0002_alter_tags_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="business",
            field=models.ForeignKey(
                blank=True,
                help_text="商家 或 平台",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="business",
                to="account.business",
                verbose_name="商家",
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="对当前这笔记录打上适合的标签，便于后期按标签查找账单记录",
                null=True,
                to="tag.tags",
                verbose_name="标签",
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="expend_side",
            field=models.ForeignKey(
                blank=True,
                help_text="花钱的一方",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expend_side",
                to=settings.AUTH_USER_MODEL,
                verbose_name="支出方",
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="income_side",
            field=models.ForeignKey(
                blank=True,
                help_text="收钱的一方",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="income_side",
                to=settings.AUTH_USER_MODEL,
                verbose_name="收入方",
            ),
        ),
    ]
