# Generated by Django 5.0.6 on 2024-06-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0008_charge_business_charge_tags_alter_charge_expend_side_and_more",
        ),
        ("tag", "0002_alter_tags_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="对当前这笔记录打上适合的标签，便于后期按标签查找账单记录",
                to="tag.tags",
                verbose_name="标签",
            ),
        ),
    ]
