# Generated by Django 5.0.6 on 2024-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_alter_charge_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="created_at",
            field=models.DateField(verbose_name="发生时间"),
        ),
    ]
