# Generated by Django 5.0.6 on 2024-06-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
        ("work", "0002_alter_skill_skill_name_alter_work_work_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="people",
            options={"verbose_name": "人", "verbose_name_plural": "人"},
        ),
        migrations.AlterField(
            model_name="people",
            name="people_comments",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="备注"
            ),
        ),
        migrations.AlterField(
            model_name="people",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="work.skill",
                verbose_name="技能",
            ),
        ),
        migrations.AlterField(
            model_name="people",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="work.work",
                verbose_name="工作",
            ),
        ),
    ]
