# Generated by Django 5.0.6 on 2024-06-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=200, verbose_name="标签名")),
                (
                    "tag_comments",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "标签管理",
                "verbose_name_plural": "标签管理",
            },
        ),
    ]
