# Generated by Django 5.0.6 on 2024-06-15 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "标签", "verbose_name_plural": "标签"},
        ),
    ]
