# Generated by Django 5.0.6 on 2024-06-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_alter_tags_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="tag_name",
            field=models.CharField(max_length=200, unique=True, verbose_name="标签名"),
        ),
    ]
