# Generated by Django 5.0.6 on 2024-06-14 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")], verbose_name="是否启用"
                    ),
                ),
                (
                    "account_type",
                    models.IntegerField(
                        choices=[(0, "商家"), (1, "个人")], default=0, verbose_name="账户类型"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "账户信息",
                "verbose_name_plural": "账户信息",
            },
        ),
    ]
