# Generated by Django 5.0.6 on 2024-06-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_profile_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="alipay",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="支付宝"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="电子邮箱"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="电话"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="wechat",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="微信号"
            ),
        ),
    ]
