# Generated by Django 5.0.6 on 2024-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profile_alipay_profile_email_profile_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.IntegerField(
                choices=[(0, "商家"), (1, "个人")], default=1, verbose_name="账户类型"
            ),
        ),
    ]
