# Generated by Django 5.0.6 on 2024-06-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=20, verbose_name="商家名称")),
                (
                    "business_comments",
                    models.TextField(max_length=200, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "商家",
                "verbose_name_plural": "商家",
            },
        ),
    ]
