# Generated by Django 5.0.6 on 2024-06-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="business_comments",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="备注"
            ),
        ),
    ]
