# Generated by Django 5.0.6 on 2024-06-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_business_business_comments"),
        ("tag", "0002_alter_tags_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="打上合适的标签，便于后期按标签查找账单记录",
                null=True,
                to="tag.tags",
                verbose_name="标签",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="打上合适的标签，便于后期按标签查找账单记录",
                null=True,
                to="tag.tags",
                verbose_name="标签",
            ),
        ),
    ]
