# Generated by Django 5.0.6 on 2024-06-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=200, verbose_name="技能")),
            ],
            options={
                "verbose_name": "技能",
                "verbose_name_plural": "技能",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_name", models.CharField(max_length=200, verbose_name="工作")),
            ],
            options={
                "verbose_name": "工作",
                "verbose_name_plural": "工作",
            },
        ),
    ]
