# Generated by Django 5.0.6 on 2024-06-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="skill_name",
            field=models.CharField(max_length=200, unique=True, verbose_name="技能"),
        ),
        migrations.AlterField(
            model_name="work",
            name="work_name",
            field=models.CharField(max_length=200, unique=True, verbose_name="工作"),
        ),
    ]
