# Generated by Django 5.0.6 on 2024-06-16 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0002_alter_skill_skill_name_alter_work_work_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "成就",
                "verbose_name_plural": "成就",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="公司或组织的名称",
                        max_length=200,
                        unique=True,
                        verbose_name="名称",
                    ),
                ),
                (
                    "company_description",
                    models.TextField(
                        help_text="公司或组织的描述或说明", max_length=200, verbose_name="描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "公司 / 组织",
                "verbose_name_plural": "公司 / 组织",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        help_text="部门名称", max_length=200, unique=True, verbose_name="名称"
                    ),
                ),
                (
                    "department_description",
                    models.TextField(
                        help_text="对当前部门的描述", max_length=200, verbose_name="描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "begin_at",
                    models.DateField(blank=True, null=True, verbose_name="在职时间「起始」"),
                ),
                (
                    "end_at",
                    models.DateField(blank=True, null=True, verbose_name="在职时间「结束」"),
                ),
                (
                    "work_content",
                    models.TextField(
                        blank=True, max_length=5000, null=True, verbose_name="工作内容"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "archievement",
                    models.ManyToManyField(
                        blank=True, null=True, to="work.archievement", verbose_name="成就"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="work.company",
                        verbose_name="公司",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="work.department",
                        verbose_name="部门",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, null=True, to="work.skill", verbose_name="技能"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="姓名",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="work.work",
                        verbose_name="职位",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作经历",
                "verbose_name_plural": "工作经历",
            },
        ),
    ]
