# Generated by Django 5.0.6 on 2024-06-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0005_archievement_arch_description_archievement_arch_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archievement",
            name="arch_name",
            field=models.CharField(max_length=200, unique=True, verbose_name="成就"),
        ),
    ]
