# Generated by Django 5.0.6 on 2024-06-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0007_archievement_created_at_archievement_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_description",
            field=models.TextField(
                blank=True,
                help_text="对当前部门的描述",
                max_length=200,
                null=True,
                verbose_name="描述",
            ),
        ),
    ]
