# Generated by Django 5.0.6 on 2024-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0009_alter_work_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_description",
            field=models.TextField(
                blank=True,
                help_text="公司或组织的描述或说明",
                max_length=200,
                null=True,
                verbose_name="描述",
            ),
        ),
    ]
